services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # 🔁 esse override é só local
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://ghostlab:ghostlab@db:5432/ghostlab
    volumes:
      - .:/app
      - ./app/uploads:/app/uploads

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ghostlab
      POSTGRES_PASSWORD: ghostlab
      POSTGRES_DB: ghostlab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
